name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instalar Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Puedes especificar una versión específica si lo deseas

      # Verificar la instalación de Flutter
      - name: Verify Flutter installation
        run: flutter doctor

      # Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # Analizar el código
      - name: Analyze project source
        run: flutter analyze

      # Ejecutar pruebas
      - name: Run tests
        run: flutter test
