name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c贸digo
      - uses: actions/checkout@v4

      # Paso 2: Instalar Flutter usando flutter-action
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Usa la versi贸n estable de Flutter

      # Paso 3: Verificar la instalaci贸n de Flutter
      - name: Verify Flutter installation
        run: flutter doctor

      # Paso 4: Instalar dependencias del proyecto
      - name: Install dependencies
        run: flutter pub get

      # Paso 5: Analizar el c贸digo
      - name: Analyze project source
        run: flutter analyze

      # Paso 6: Ejecutar pruebas
      - name: Run tests
        run: flutter test
